# -*- coding: utf-8 -*-
"""python_patterns_intermediate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AHK2rY9pKxLUnxUCJqmXOxWrof3v38p-

# Patterns
"""

n = int(input())
rows = 1
while rows<=n:
  col = 1
  p = 0
  while col<=rows:
    print(p+rows,end = '')
    p = p + 1
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
p = 1
while rows<=n:
  col = 1
  while col<=rows:
    print(p,end = '')
    p = p + 1
    col = col + 1
  print()
  rows = rows + 1

n = int(input())
rows = 1
while rows<=n:
  col = rows
  while col>=1:
    print(col,end = '')
    col = col - 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col<=rows:
    print("1",end = '')
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col<=rows:
    print(chr(64 + col),end = '')
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col<=rows:
    print(chr(64 + rows),end = '')
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col<=rows:
    print(chr(64 + rows + col -1),end = '')
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col<=n - rows + 1 :
    print("*",end = '')
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col<=n - rows + 1 :
    print(rows,end = '')
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  spaces = 1
  stars = 1
  while spaces<=n-rows:
    print(" ",end = '')
    spaces = spaces + 1
  while stars<=rows:
    print("*",end = '')
    stars = stars + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  spaces = 1
  stars = 1
  while spaces<=n-rows:
    print(" ",end = '')
    spaces = spaces + 1
  while stars<=rows:
    print(stars,end = '')
    stars = stars + 1
  rows = rows + 1
  print()