# -*- coding: utf-8 -*-
"""python_patterns.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AHK2rY9pKxLUnxUCJqmXOxWrof3v38p-

# Patterns
"""

n = int(input())
rows = 1
while rows <= n:
  col = 1
  while col<=n:
    print("*", end = '')
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
row = 1
while row<=n:
  col = 1
  while col<=n:
    print(n - col + 1,end = '')
    col = col + 1
  row = row+1
  print()

n = int(input())
row = 1
while row<=n:
  col = 1
  while col<=n:
    print(col + row - 1,end = '')
    col = col + 1
  row = row+1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col <= rows:
    print(rows, end = '')
    col = col + 1
    
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col <= rows:
    print(, end = '')
    col = col + 1
    
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col <=n:
    print(chr(64+col),end = '')
    col = col + 1
  rows = rows + 1
  print()

n = int(input())
rows = 1
while rows<=n:
  col = 1
  while col<=n:
    print(chr(64+col+rows-1),end = '')
    col = col + 1
  rows = rows + 1
  print()